[package]
name = "lisp"
version = "0.1.0"
authors = ["saffronsnail"]

[dependencies]
# readline replacement
rustyline = "1.0.0"

# Combinatorial parsing library
nom = "^3.2"

# High-level bindings for gmp, mpfr, and mpc
rug = "0.9.2"
